### ISSUE TITLE
Let's not locking the orientation

### ISSUE THREAD

**Issue by sleepylee** [nhphong/nimble-surveys#10]

**Comment by nhphong** [comment]
@sleepylee Check out this commit: 
https://github.com/nhphong/nimble-surveys/pull/12/commits/fc356211f9a6fd77f35ab6e03dbccd72d1cc93d4

**Comment by nhphong** [comment]
@sleepylee can we close this issue?

**Comment by sleepylee** [comment]
yes please do 🙏
