### ISSUE TITLE
Vertical pager indicator issue

### ISSUE THREAD

**Issue by luongvo** [nhphong/nimble-surveys#14]
I see you're using RecyclerView to implement vertical indicator for pager. It led to a an issue that all indicator bullets are not aligned to vertical center. Any reason why did you go by this way? 🤔 Could you propose a solution to make it vertically center?
![image](https://user-images.githubusercontent.com/16315358/55976976-df802a80-5cb7-11e9-9750-5933d916a19e.png)

**Comment by nhphong** [comment]
Yes @luongvo, we can make it vertically centered. I will create a pull request soon

**Comment by nhphong** [comment]
@luongvo Check it out https://github.com/nhphong/nimble-surveys/pull/17
