### ISSUE TITLE
BulletsAdapter should not constrain to MainPagerAdapter

### ISSUE THREAD

**Issue by luongvo** [nhphong/nimble-surveys#16]
As your implementation [here](https://github.com/nhphong/nimble-surveys/blob/b15de231ae81fb99d67dd9b68af7baa57d9c38f8/app/src/main/java/com/nhphong/nimblesurveys/views/adapter/BulletsAdapter.kt#L33), `syncWithViewPager` receives a pager as `ViewPager` but does sth as `MainPagerAdapter`, what happens if we pass another Pager into this `BulletsAdapter`? I guess it will not work anymore, anw `BulletsAdapter` should not constrain to `MainPagerAdapter` 🤔

**Comment by nhphong** [comment]
Agree with @luongvo, we should not make it dependent on `MainPagerAdapter`.
I have updated the code, please check it out in https://github.com/nhphong/nimble-surveys/pull/18
