### ISSUE TITLE
Question for the mix of LiveData and RxJava at the same time

### ISSUE THREAD

**Issue by sleepylee** [nhphong/nimble-surveys#5]
Hi Phong,
First of all, we'd like to say that we really appreciate your efforts in completing the code assignment. So I and the team will take some times to review and post the feedback directly here, please feel free to discuss or giving your opinion in case there is any wrong catch, or require further declaration.

The first thing I noticed is that you're combining both RxJava and LiveData for Event pub/sub communication in between your components. Could you please give us a few reasons why wouldn't we go with only 1 side? 

Imo, maintaining such projects could lead to a larger volume in requirements to the developers, they will need to learn both, whilst in fact, you can do the same with, perhaps, just RxJava with PublishSubject or any other similar components or vice versa.

**Comment by nhphong** [comment]
Hi Trung,
Both LiveData and RxJava have their own advantages and disadvantages. I decided to use all of them to utilize the benefits from each pattern.

- LiveData is lifecycle-aware. It respects the observer's life cycle and it won't emit changes when the observer is in a passive state. Activities or Fragments are instantly unsubscribed when they finish their life cycle (so no memory leak). With RxJava, we have to manually handle that un-subscription
- Using LiveData, if a lifecycle becomes inactive, it receives the latest data upon becoming active again. With RxJava, we have to re-subscribe the data in `onResume()`
-----
- However, LiveData is not nature of a Reactive Stream. Suppose we have a `LiveData<Int>` for which the value is set to `1`, `2`, `3`, `4` in parallel (by multiple threads), what do we expect when subscribing to it? Unlike RxJava, the observer can only receive the latest value, not all four values.
- LiveData, as its name suggests, should only be used as a LIVE data (data that is live). It should not be considered as a stream of data or events.
