### ISSUE TITLE
Accessibility and suggestion to make it better

### ISSUE THREAD

**Issue by sleepylee** [nhphong/nimble-surveys#7]
From what I observe [here](https://github.com/nhphong/nimble-surveys/blob/5d4d688a93cabca071bfe3b2cc51bd73b116c694/app/src/main/java/com/nhphong/nimblesurveys/data/api/AccessTokenApi.kt#L20), it seems like a pure conversion from java to kotlin for the implementation of static final field, and companion object does cost too, so instead, I'd suggest to define const at top level class within the same file, also, since they are only retrievable privately, how about specify them also as `private val const`, how do you think?

**Comment by nhphong** [comment]
Yes it should be `private`. Thanks for your suggestion 👍 
But I don't quite get what you mean by "define const at top level class within the same file".

**Comment by nhphong** [comment]
Is it what you meant
```
private const val DEFAULT_GRANT_TYPE = "password"
private const val DEFAULT_USERNAME = "carlos@nimbl3.com"
private const val DEFAULT_PASSWORD = "antikera"

interface AccessTokenApi {

  @POST("oauth/token")
  fun renewAccessToken(
    @Body credentials: Credentials = Credentials(
      grantType = DEFAULT_GRANT_TYPE,
      userName = DEFAULT_USERNAME,
      password = DEFAULT_PASSWORD
    )
  ): Observable<AccessToken>
}
```

**Comment by nhphong** [comment]
Check out this PR https://github.com/nhphong/nimble-surveys/pull/12
