### ISSUE TITLE
Misc in layout

### ISSUE THREAD

**Issue by sleepylee** [nhphong/nimble-surveys#8]
Take `activity_main.xml` as an example, I found a few issues here:
- Naming on the component's id doesn't formulate a consistent convention.
- Component styling could be managed better for future extension (just a reminder on the question we asked during the screening process regarding styling a simple text view).

**Comment by nhphong** [comment]
Thanks for your recommendation. I will update the code.

**Comment by nhphong** [comment]
@sleepylee check out this PR
https://github.com/nhphong/nimble-surveys/pull/12
